# -*- coding: utf-8 -*-
"""MSC Assignment 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MjPBhJrbIrB65ERmJsMpQ4F_xZ7ypRUA
"""

from google.colab import files
uploded= files.upload()
 
import pandas as pd
 
dataset= pd.read_excel('DataSet.xlsx').fillna(0)

dataset["BODout"]

dataset

dataset["BODout"].median()

dataset["BODout"].var()

statdf= dataset.describe()

statdf

Range = statdf.loc["max"]-statdf.loc["min"]
Range

IQR = statdf.loc["75%"]-statdf.loc["25%"]
IQR

import matplotlib.pyplot as plt

#Scatter plot for BOD

x = dataset["Days"]
y = dataset["BODout"]

plt.scatter(x, y)
plt.show()

#Scatter plot for PH

x = dataset["Days"]
y = dataset["PH"]

plt.xlabel("Plot for PH")
plt.ylabel("Time(Days)")

plt.scatter(x, y)
plt.show()

#Box plot for BOD
y = dataset["BODout"]
plt.xlabel("Box Plot for BOD")
plt.ylabel("Values")

plt.boxplot(y)
plt.show()

#Box plot for PH
y = dataset["PH"]
plt.xlabel("Box Plot for PH")
plt.ylabel("Values")

plt.boxplot(y)
plt.show()

#Time series plot for BOD
plt.plot(dataset["Days"],dataset["BODout"],color ="red")

plt.xlabel("Time (Days)")
plt.ylabel("BOD Values")
plt.show()

#Time series plot for PH
plt.plot(dataset["Days"],dataset["PH"],color ="green")

plt.xlabel("Time (Days)")
plt.ylabel("BOD Values")
plt.show()

#Frequency of observations for PH
dataset['PH'].value_counts()

#Frequency of observations for BOD
dataset['BODout'].value_counts()

#Histogram for BOD
plt.xlabel("BOD Values)")
plt.ylabel("Frequency")
dataset['BODout'].hist(bins=50)
plt.show()

#Histogram for PH
plt.xlabel("PH Values)")
plt.ylabel("Frequency")
dataset['PH'].hist(bins=50)
plt.show()

#cumulative frequency plot for PH
dataset['PH'].hist(cumulative=True, density=1, bins=100)
plt.xlabel("PH Values)")
plt.ylabel("Cumulative Frequency")
plt.show()

#cumulative frequency plot for BOD
dataset['BODout'].hist(cumulative=True, density=1, bins=100)
plt.xlabel("BOD Values)")
plt.ylabel("Cumulative Frequency")
plt.show()

